### ISSUE TITLE
debugPrint incompatibility

### ISSUE THREAD

**Issue by SalahAdDin** [iamsalnikov/colorize#10] opened 2022-03-05 15:35 UTC
Hello,

I have been using this package for a long time for easy debugging on the console.

With the last **flutter** version and the **lint** update we are getting the next warning:
```
Avoid `print` calls in production code.
```

As a solution, we can either use `debugPrint` or a conditional for `kDebugMode`.

The second one works fine, but the first one gives us a bug:
```
The argument type 'Colorize' can't be assigned to the parameter type 'String?'.
```

How could we solve this?

**Comment by xscotophilic** [comment] 2022-10-24 08:33
It's not a bug, when you use `debugPrint`, it doesn't support any datatype other than `String?` which is String or null. The concept null-safety was introduced after dart 2.3, you can read about it [here](https://dart.dev/null-safety#null-safety-principles)

So if you want to use debugPrint, covert objects to String using .toString() method.
```
debugPrint(1.toString());
```

**Comment by xscotophilic** [comment] 2022-10-24 08:33
@SalahAdDin you can close the issue now.

**Closed as completed** 2022-10-24 18:12 UTC
